modifiers:
  HOME: "{HOME}"
  BASE_OUT_FOLDER: "{HOME}/MyTmp/AirbusHelicopterAccelerometer/train_127_126_8-adam-var-w/{ENCODER_NAME}-{TIME}"

  ENCODER_NAME: "{ENCODER_NAME}"
  TRANSF_DEGREE: "{TRANSF_DEGREE}"

  BATCH_SIZE: 200  # 1677
  BATCH_SIZE_VAL: 200  # 594
  NUM_WORKERS: 24

  MAX_EPOCH: 50
  RESTART_EPOCH: true
  N_SAVE_INTER_EPOCH: 1_000_000
  GRAD_ACCUM: 1

base_out_folder: "{BASE_OUT_FOLDER}"
log_dir: "{BASE_OUT_FOLDER}"
name_save_ckpt: "valid"
stages_trainer_sorted: ["train", "valid"]
cnn_benchmark: true
seed: null

distributed_data_parallel: true
node_rank: 0
dist_address: "127.0.0.1:1238"
world_size: 1

engine:
  model:
    name: "Feature2DAirbusHelicopterAccelerometer"
    half: false
    find_unused_parameters: false
    args:
      encoder_name: "{ENCODER_NAME}"
      input_dim: 64
      variational: true
      verbose: false
    resume:
      load_model_fn: "no.ckpt"
      save_model_dir: "{BASE_OUT_FOLDER}/models"
      save_tmp_model_fn: "{HOME}/MyTmp/AirbusHelicopterAccelerometer/train_127_126_8-adam-var-w/tmp_model.ckpt"
      load_optimizer: false
      load_scheduler: false
      save_all: true
      strict: false

train:
  n_log_interval: 1_000_000
  n_save_inter_epoch: "{N_SAVE_INTER_EPOCH}"
  max_epochs: "{MAX_EPOCH}"
  restart_epoch: "{RESTART_EPOCH}"
  grad_accum: "{GRAD_ACCUM}"
  non_blocking: true

clipper:
  name: null
  args: null

loader:
  train:
    batch_size: "{BATCH_SIZE}"
    num_workers: "{NUM_WORKERS}"
    pin_memory: true
    drop_last: true
  valid:
    batch_size: "{BATCH_SIZE_VAL}"
    num_workers: "{NUM_WORKERS}"
    pin_memory: true
    drop_last: false

dataset:
  name: "DatasetAirbusHelicopterAccelerometer"
  train:
    dir_matrix: "~/MyTmp/AirbusHelicopterAccelerometer/data-db/dftrain_127_126_8-1677-120"
#    norm_path: "~/MyTmp/AirbusHelicopterAccelerometer/data-db/normalization_127_126_8.json"
    norm_max_min: true
    weight: true
    transf_degree: "{TRANSF_DEGREE}"
  valid:
    dir_matrix: "~/MyTmp/AirbusHelicopterAccelerometer/data-db/dfvalid_127_126_8-594-120"
#    norm_path: "~/MyTmp/AirbusHelicopterAccelerometer/data-db/normalization_127_126_8.json"
    norm_max_min: true
    weight: true
    labels_path: "../data/dfvalid_groundtruth.csv"
    transf_degree: "{TRANSF_DEGREE}"

optimizer:
#  name: "SGD"
#  args:
#    lr: 0.0001
#    weight_decay: 0.0001
  name: "AdamW"
  args:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1.e-08
    weight_decay: 0.0001

# a ** N = 0.01
# a = 10**(math.log10(0.01) / N)
scheduler:
  name: "StepLR"
  step_scheduler_at_save: false
  args:
    step_size: 1.
    last_epoch: -1
    # 0.1 (2)  0.6309573444801932 (3)  0.6309573444801932 (10)  0.9120108393559098 (50)  0.954992586021436 (100)
    gamma: 0.9120108393559098

loss:
  name: "L2"
  args: null

metric:
  train:
    - name: "L2"
      args: null
  valid:
    - name: "L2"
      args: null
#    - name: "AUC"
#      args: null
